version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: redbull-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - redbull-app
    networks:
      - redbull-network

  redbull-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redbull-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - app-logs:/app/logs
    depends_on:
      - db
    networks:
      - redbull-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    container_name: redbull-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql:ro
      - mysql-logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - redbull-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redbull-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - redbull-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

  watchtower:
    image: containrrr/watchtower
    container_name: redbull-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    networks:
      - redbull-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: redbull-promtail
    restart: unless-stopped
    volumes:
      - app-logs:/var/log/app:ro
      - mysql-logs:/var/log/mysql:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    networks:
      - redbull-network
    depends_on:
      - redbull-app

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  app-logs:
    driver: local
  mysql-logs:
    driver: local

networks:
  redbull-network:
    driver: bridge
